# Generated by Django 3.2.19 on 2023-05-11 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=10)),
                ('acct_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('active_user', models.BooleanField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25)),
                ('level_of_study', models.CharField(choices=[('Graduate', 'MASTERS'), ('Graduate', 'PHD'), ('Undergraduate', 'BACHELORS')], max_length=25)),
                ('college', models.CharField(choices=[('College of Information and Sciences', 'CICS'), ('Other', 'other')], max_length=35)),
                ('major', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Data Science', 'Data Science'), ('Accounting', 'Accounting'), ('Pyschology', 'Pyschology'), ('Undecided', 'Undecided')], max_length=25)),
                ('sleep_habits', models.CharField(choices=[('Before 9pm', 'Before 9pm'), ('Before 11pm', 'Before 9pm'), ('Before 1am', 'Before 1am')], max_length=25)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
