# Generated by Django 4.2 on 2023-05-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webappl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staus', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('ignored', 'IGNORED')], default='pending', max_length=25)),
                ('date_sent', models.DateField(default=django.utils.timezone.now)),
                ('recipientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipientid', to=settings.AUTH_USER_MODEL)),
                ('requesterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesterid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='acct_creation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='active_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('AVG', 'Average'), ('DIRTY', 'Dirty')], default='CLEAN', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(choices=[('EDUC', 'College of Education'), ('ENG', 'College of Engineering'), ('CHFA', 'College of Humanities and Fine Arts'), ('CICS', 'College of Information and Computer Sciences'), ('CNS', 'College of Natural Sciences'), ('EMCON', 'Elaine Marieb College of Nursing'), ('CSBS', 'College of Social and Behavioral Sciences'), ('ISOM', 'Isenberg School of Management'), ('SPHHS', 'School of Public Health & Health Sciences'), ('SSA', 'Stockbridge School of Agriculture'), ('OTHER', 'Other')], default='EDUC', max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='duration',
            field=models.CharField(choices=[('ONE', 'One Season'), ('TWO', 'Two Seasons'), ('THREE', 'Three Seasons'), ('FOUR', 'Four Seaons')], default='ONE', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='housing',
            field=models.CharField(choices=[('HAVE', 'Have a place'), ('NEED', 'Need a place')], default='HAVE', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='level_of_study',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('GA', 'Graduate')], default='UG', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(choices=[('ACC', 'Accounting'), ('AAS', 'Afro-American Studies'), ('AI', 'Alternative Investments'), ('ASAB', 'Animal Science, Animal Biotechnology, and Biomedical Sciences'), ('ANTH', 'Anthropology'), ('ACFM', 'Arboriculture and Community Forest Management'), ('ARCH', 'Architecture'), ('ART', 'Art'), ('AED', 'Art Education'), ('ARTH', 'Art History'), ('ASTR', 'Astronomy'), ('BMB', 'Biochemistry and Molecular Biology'), ('BIO', 'Biology'), ('BME', 'Biomedical Engineering'), ('BST', 'Biostatistics'), ('BCT', 'Building and Construction Technology'), ('BA', 'Business Analytics'), ('CHE', 'Chemical Engineering'), ('CHEM', 'Chemistry'), ('CHN', 'Chinese Language and Literature'), ('CE', 'Civil Engineering'), ('CLAS', 'Classics'), ('COMM', 'Communication'), ('CDIS', 'Communication Disorders'), ('CHE', 'Community Health Education'), ('COLIT', 'Comparative Literature'), ('CS', 'Computer Science'), ('DANCE', 'Dance'), ('DACS', 'Data Analytics and Computational Social Science'), ('ECON', 'Economics'), ('EDUC', 'Education'), ('ECE', 'Electrical and Computer Engineering'), ('EM', 'Engineering Management'), ('ENG', 'English'), ('EVCON', 'Environmental Conservation'), ('EVE', 'Environmental Engineering'), ('EHS', 'Environmental Health Sciences'), ('ENVS', 'Environmental Science'), ('EPID', 'Epidemiology'), ('FILM', 'Film Studies through BDIC'), ('FIN', 'Finance'), ('FSCI', 'Food Science'), ('FREN', 'French & Francophone Studies'), ('GEOG', 'Geography'), ('GEOL', 'Geology'), ('GEOSCI', 'Geosciences'), ('GER', 'German and Scandinavian Studies'), ('HPM', 'Health Policy and Management'), ('HLL', 'Hispanic Literatures and Linguistics'), ('HIST', 'History'), ('HAA', 'History of Art and Architecture'), ('HORT', 'Horticultural Science'), ('HTM', 'Hospitality and Tourism Management'), ('IE', 'Industrial Engineering'), ('INFO', 'Informatics'), ('ITAL', 'Italian Studies'), ('JPN', 'Japanese Language & Literature'), ('JOUR', 'Journalism'), ('JUDS', 'Judaic Studies'), ('KIN', 'Kinesiology'), ('LS', 'Labor Studies'), ('LARCH', 'Landscape Architecture'), ('LCON', 'Landscape Contracting'), ('LS', 'Legal Studies'), ('LING', 'Linguistics'), ('MGMT', 'Management'), ('MKTG', 'Marketing'), ('MATH', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MICRO', 'Microbiology'), ('MES', 'Middle Eastern Studies'), ('MUS', 'Music'), ('NRC', 'Natural Resource Conservation'), ('NB', 'Neuroscience and Behavior'), ('NURS', 'Nursing'), ('NUTR', 'Nutrition'), ('OIM', 'Operations and Information Management'), ('PHIL', 'Philosophy'), ('PHYS', 'Physics'), ('PBIO', 'Plant Biology'), ('PSS', 'Plant and Soil Science'), ('POL', 'Political Science'), ('PSE', 'Polymer Science and Engineering'), ('PORT', 'Portuguese'), ('PMED', 'Pre-Medical, Pre-Health'), ('PVT', 'Pre-Veterinary'), ('PSYCH', 'Psychology'), ('PHS', 'Public Health Sciences'), ('PPA', 'Public Policy and Administration'), ('RP', 'Regional Planning'), ('RECON', 'Resource Economics'), ('REES', 'Russian and East European Studies'), ('STPEC', 'Social Thought and Political Economy'), ('SOC', 'Sociology'), ('SPAN', 'Spanish'), ('SM', 'Sport Management'), ('SFF', 'Sustainable Food and Farming'), ('SH', 'Sustainable Horticulture'), ('SSCI', 'Sustainability Science'), ('THEA', 'Theater'), ('TM', 'Turfgrass Management'), ('VETECH', 'Veterinary Technology'), ('WGSS', 'Women, Gender, Sexuality Studies')], default='ACC', max_length=65),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_habit',
            field=models.CharField(choices=[('EB', 'Early Bird'), ('AVG', 'Average'), ('NO', 'Night Owl')], default='EB', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_habit',
            field=models.CharField(choices=[('NG', 'No Overnight Guests'), ('YG', 'Overnight Guests')], default='NG', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_season',
            field=models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], default='FALL', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('MS', 'Graduate'), ('PHD', 'PhD')], default='FR', max_length=25),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
