# Generated by Django 3.2.19 on 2023-05-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webappl', '0003_rename_requests_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
